#!/bin/sh

killall looping

echo chatserver
./chatserver >/dev/null &
echo "Starting Update Server"
./update_server >/dev/null &

sleep 1
./server3 -a1 -d
sleep 1
./server3 -a2 -d
sleep 1
./server3 -a3 -d
sleep 1
./server3 -a4 -d
sleep 1
./server3 -a5 -d
sleep 1
./server3 -a6 -d
sleep 1
./server3 -a7 -d
sleep 1
./server3 -a8 -d
sleep 1
./server3 -a9 -d
sleep 1
./server3 -a10 -d
sleep 1
./server3 -a11 -d
sleep 1
./server3 -a12 -d
sleep 1
./server3 -a13 -d
sleep 1
./server3 -a14 -d
sleep 1
./server3 -a15 -d
sleep 1
./server3 -a16 -d
sleep 1
./server3 -a17 -d
sleep 1
./server3 -a18 -d
sleep 1
./server3 -a19 -d
sleep 1
./server3 -a20 -d
sleep 1
./server3 -a21 -d
sleep 1
./server3 -a22 -d
sleep 1
./server3 -a23 -d
sleep 1
./server3 -a24 -d
sleep 1
./server3 -a25 -d
sleep 1
./server3 -a26 -d
sleep 1
#./looping & # a27
#sleep 1
./server3 -a28 -d
sleep 1
./server3 -a29 -d
sleep 1
./server3 -a30 -d
sleep 1
./server3 -a31 -d
sleep 1
./server3 -a32 -d
sleep 1
./server3 -a33 -d
sleep 1
./server3 -a34 -d
sleep 1
./server3 -a35 -d
sleep 1
./server3 -a36 -d
sleep 1
./server3 -a37 -d
sleep 1
echo DONE